/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "INIT.h"
#include <stdio.h>
#include <stdlib.h>
#include <openssl/sha.h>
#include <string.h>
int *gettransactionid_100_svc(void *argp, struct svc_req *rqstp)
{
	static int result;

	FILE *bd;
	bd = fopen("bancoDados.csv", "r");
	if (bd == NULL)
	{
		bd = fopen("bancoDados.csv", "w");
		fprintf(bd, "TransactionId,Challenge,Seed,Winner\n");
		fprintf(bd, "0,1,-1,-1\n");
		fclose(bd);
		result = 0;
	}
	else
	{
		char aux[100], saida[100];
		while (fscanf(bd, "%s", aux) != EOF)
		{
			strcpy(saida, aux);
		}
		char *pt;
		pt = strtok(saida, ",\n");
		result = atoi(pt);
		fclose(bd);
	}
	return &result;
}

int *getchallenge_100_svc(int *argp, struct svc_req *rqstp)
{
	static int result = -1;
	FILE *bd;
	bd = fopen("bancoDados.csv", "r");
	if (bd != NULL)
	{
		char *line = NULL;
		size_t len = 0;
		ssize_t read;
		int i = 0;
		while ((read = getline(&line, &len, bd)) != -1)
		{
			if (i == 0)
				i++;
			else
			{
				char *pt;
				pt = strtok(line, ",\n");
				int a = atoi(pt);
				if (a == *argp)
				{
					pt = strtok(NULL, ",");
					result = atoi(pt);
					break;
				}
			}
		}
	}
	fclose(bd);
	return &result;
}

status *
getseed_100_svc(int *argp, struct svc_req *rqstp)
{
	static status result;
	FILE *bd;
	char test[100];
	bd = fopen("bancoDados.csv", "r");
	int i = 0;
	if (bd != NULL)
	{
		while (fscanf(bd, "%[^\n] ", test) != EOF)
		{
			if (i == 0)
				i++;
			else
			{
				char *pt;
				pt = strtok(test, ",\n");
				int a = atoi(pt);
				if (a == *argp)
				{
					pt = strtok(NULL, ",\n");
					result.challenge=atoi(pt);
					pt = strtok(NULL, ",\n");
					result.seed.seed_len=strlen(pt);
					result.seed.seed_val=strdup(pt);
					pt = strtok(NULL, ",\n");
					
					result.status=*(gettransactionstatus_100_svc(argp, rqstp));
					break;
				}
			}
		}
	}
	fclose(bd);
	return &result;
}

int *getwinner_100_svc(int *argp, struct svc_req *rqstp)
{
	static int result;
	FILE *bd;
	char test[100];
	bd = fopen("bancoDados.csv", "r");
	int i = 0;
	result = -1;
	if (bd != NULL)
	{
		while (fscanf(bd, "%[^\n] ", test) != EOF)
		{
			if (i == 0)
				i++;
			else
			{
				char *pt;
				pt = strtok(test, ",\n");
				int a = atoi(pt);
				if (a == *argp)
				{
					pt = strtok(NULL, ",\n");
					pt = strtok(NULL, ",\n");
					pt = strtok(NULL, ",\n");
					int aux = atoi(pt);
					if (aux != -1)
					{
						result = aux;
					}
					else if (aux == -1)
					{
						result = 0;
					}
					else
					{
						result = -1;
					}
					break;
				}
			}
		}
	}
	fclose(bd);
	return &result;
}

int *submitchallenge_100_svc(info *argp, struct svc_req *rqstp)
{
	static int result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *gettransactionstatus_100_svc(int *argp, struct svc_req *rqstp)
{
	static int result;
	FILE *bd;
	bd = fopen("bancoDados.csv", "r");
	result = -1;
	if (bd != NULL)
	{
		char *line = NULL;
		size_t len = 0;
		ssize_t read;
		int i = 0;
		while ((read = getline(&line, &len, bd)) != -1)
		{

			if (i == 0)
				i++;
			else
			{
				char *pt;
				pt = strtok(line, ",");
				int a = atoi(pt);
				if (a == *argp)
				{
					pt = strtok(NULL, ",");
					pt = strtok(NULL, ",");
					pt = strtok(NULL, ",");
					int aux = atoi(pt);
					if (aux != -1)
					{
						result = 0;
					}
					else if (aux == -1)
					{
						result = 1;
					}
					else
						result = -1;
					break;
				}
			}
		}
	}
	fclose(bd);
	return &result;
}
