/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "INIT.h"

bool_t
xdr_tabela (XDR *xdrs, tabela *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->transactionId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->challenge))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->seed.seed_val, (u_int *) &objp->seed.seed_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->winner))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_info (XDR *xdrs, info *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->transactionId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->clientId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seed))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_status (XDR *xdrs, status *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->challenge))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->seed.seed_val, (u_int *) &objp->seed.seed_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}
